# Generated by Django 5.1.15 on 2026-01-04 06:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('steam_id', models.CharField(help_text='Steam ID of the user', max_length=255, unique=True)),
                ('steam_api_key', models.CharField(help_text='Steam API key (should be encrypted in production)', max_length=255)),
                ('trade_url', models.CharField(help_text='Steam trade URL', max_length=500)),
                ('wallet_address', models.CharField(help_text='TON wallet address for withdrawals', max_length=255)),
                ('balance_active', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Active balance available for use', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_frozen', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Frozen balance (held in escrow)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SkinListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(help_text='Steam Item Asset ID', max_length=255)),
                ('market_name', models.CharField(help_text='Market name of the skin item', max_length=255)),
                ('price_ton', models.DecimalField(decimal_places=8, help_text='Price in TON', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Current status of the listing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(help_text='User who listed the skin', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skin Listing',
                'verbose_name_plural': 'Skin Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, help_text='Order amount in TON', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('SENT', 'Sent'), ('COMPLETED', 'Completed'), ('RELEASED', 'Released'), ('DISPUTED', 'Disputed')], default='PAID', help_text='Current status of the order', max_length=20)),
                ('steam_trade_id', models.CharField(blank=True, help_text='Steam trade offer ID', max_length=255, null=True)),
                ('hold_expiry_date', models.DateTimeField(blank=True, help_text='Date when the escrow hold expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='User who purchased the skin', on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(help_text='User who sold the skin', on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='The skin listing this order is for', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.skinlisting')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
