# Generated by Django 6.0 on 2026-01-04 12:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='steam_api_key',
            field=models.CharField(blank=True, help_text='Steam API key (should be encrypted in production)', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(blank=True, db_index=True, help_text='Steam ID of the user', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='trade_url',
            field=models.CharField(blank=True, help_text='Steam trade URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='TON wallet address for withdrawals', max_length=255),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, help_text='Deposit amount in TON', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tx_hash', models.CharField(help_text='Blockchain transaction hash', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the deposit', max_length=20)),
                ('comment_code', models.CharField(help_text='Unique comment code used for deposit identification', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the deposit was confirmed', null=True)),
                ('user', models.ForeignKey(help_text='User who made the deposit', on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tx_hash'], name='core_deposi_tx_hash_d6e3cc_idx'), models.Index(fields=['status'], name='core_deposi_status_c037bb_idx'), models.Index(fields=['user', 'status'], name='core_deposi_user_id_82871c_idx')],
            },
        ),
    ]
